### ISSUE TITLE
get header API usage 

### ISSUE THREAD

**Issue by nakedkoalacapital** [ultrasoundmoney/docs#1]
issue solved

**Comment by alextes** [comment]
At a glance everything looks fine. You call our eu auction with the right path to get a header plus the slot, parent hash and validator pubkey. (same is documented here: https://ethereum.github.io/builder-specs/#/Builder/getHeader)

What is a bit surprising is that you're hardcoding the validator pubkey. It should be the pubkey of the validator of the next slot. You'll also only be able to retrieve the header for a short time, so say 1000ms before that slot starts to 1000ms after it started you may see a header. After that you may see either 204 no content or 400 slot to old responses.

So my best guess here is the validator pubkey is wrong for that slot (if you actually hardcoded it, and that validator is not the next validator in line), or you were too early / too late with calling.

Here's an example URL i know returned a header as expected during the short period one was available: https://relay-builders-eu.ultrasound.money/eth/v1/builder/header/10094322/0xf16548090682a6865173a4454ba4a41196fc37b326404d8565f0ccd29ae3f50f/0x98f801233d87b79028bb17ebafcd2e5fc502f05a0cd5a982ddfc3ffdfd52c2aabddad8510ca4c8073cc98d066d32fe52

**Comment by nakedkoalacapital** [comment]
@alextes 

Thanks for the clarification.  

Further Question: 

How would I programmatically get the next validator in line for the next block ?

**Comment by alextes** [comment]
1. i don't know off the top of my head. if you look at the beacon chain APIs you'll find it. AI says look for the "proposer duties" api call.
2. if we're in slot n, and say it started at t = 0,  after 12s period, at t = 12 slot n + 1 would start. 1000 ms before slot n + 1 starts, so t = 11, block builders will be very actively submitting blocks to us, so that when the validator / proposer for slot n + 1 calls us, usually at the start of the slot, so t = 12, we need to have a header. 1000 ms before and after that point, so t = 11 to t = 13, you should see the header we return updating fairly rapidly.
3. to build any block you need to know what previous block to build on so lets simplify and say the earliest you can start building for the next slot is in the last four seconds of the current slot, when you're quite sure what the block for the current slot is. on the beacon chain, you can only propose a block in the first 4s of each slot, so now we have 4s before the slot starts, and up to 4s after it starts where it makes sense to build blocks and pass them to the proposer through a relay. there's no point returning a header after that window, and so our relay doesn't.
